# Generated by Django 4.1.2 on 2022-11-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=20)),
                ('isnb', models.IntegerField()),
            ],
        ),
    ]
